// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqoikdpshyjivouzxqyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxb2lrZHBzaHlqaXZvdXp4cXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyNTQ0MjIsImV4cCI6MjA4NTgzMDQyMn0.D0cnTKJnYAscpBBHQlOvZgTm7jphZACHiStbX8ZkNw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});